name: "Go get diff in pr"
description: "-"
author: "Anna Polupanova"
inputs:
  headHash:
    description: "hash of HEAD commit in master"
  diff:
    description: "diff between master and PR branch"
    default: ""
  host:
    description: "server host"
outputs:
  message:
    description: "Output from the action"
runs:
  using: "docker"
  image: "Dockerfile"
